import "pkg:/source/WatchedIndicator.bs"

'-------------------------------------------------------------------------------
' init
'-------------------------------------------------------------------------------
sub init()
    m.global.observeField("watchedIndicatorStyle", "updateStyle")
    updateStyle()
end sub

'-------------------------------------------------------------------------------
' updateStyle
'-------------------------------------------------------------------------------
sub updateStyle()
    m.top.uri = WatchedIndicator.GetImageUri(m.global.watchedIndicatorStyle)
end sub
