'-------------------------------------------------------------------------------
' init
'-------------------------------------------------------------------------------
sub init()
    m.posterMask = m.top.findNode("posterMask")
    m.poster = m.top.findNode("poster")
    m.nameLabel = m.top.findNode("nameLabel")
    m.roleLabel = m.top.findNode("roleLabel")
    maskProfile = MaskAssets.GetProfile("cast-mask.png", [195, 195], [130, 130])
    m.posterMask.maskUri = maskProfile.uri
    m.posterMask.maskSize = maskProfile.size
    if maskProfile.isHd then m.posterMask.translation = [12, 6]
end sub

'-------------------------------------------------------------------------------
' onItemContentChanged
'-------------------------------------------------------------------------------
sub onItemContentChanged()
    item = m.top.itemContent
    if item = invalid then return

    m.nameLabel.text = Format.SafeString(item.title, "")
    m.roleLabel.text = Format.SafeString(item.description, "")

    imageUrl = Format.SafeString(item.HDPosterUrl, "")
    m.poster.visible = imageUrl <> ""
    m.poster.uri = imageUrl
end sub
