namespace tests
    @SGNode("HeaderDropdownMenu")
    @suite("HeaderDropdownMenu component")
    class HeaderDropdownMenuTests extends rooibos.BaseTestSuite
        @describe("declarative component contract")
        @it("declares the backgroundColor node")
        function _()
            m.assertNotInvalid(m.top.findNode("backgroundColor"))
        end function
        @it("declares the backgroundGlass node")
        function _()
            m.assertNotInvalid(m.top.findNode("backgroundGlass"))
        end function
        @it("declares the identityGroup node")
        function _()
            m.assertNotInvalid(m.top.findNode("identityGroup"))
        end function
        @it("declares the identityImageMask node")
        function _()
            m.assertNotInvalid(m.top.findNode("identityImageMask"))
        end function
        @it("declares the identityImage node")
        function _()
            m.assertNotInvalid(m.top.findNode("identityImage"))
        end function
        @it("declares the identityName node")
        function _()
            m.assertNotInvalid(m.top.findNode("identityName"))
        end function
        @it("declares the itemsGroup node")
        function _()
            m.assertNotInvalid(m.top.findNode("itemsGroup"))
        end function
    end class
end namespace
