import "pkg:/source/Format.bs"
import "pkg:/source/String.bs"
import "pkg:/source/MaskAssets.bs"
import "pkg:/source/ResolutionProfile.bs"
import "pkg:/source/ResolutionAssets.bs"

'-------------------------------------------------------------------------------
' init
'-------------------------------------------------------------------------------
sub init()
    MaskAssets.Apply(m.top.findNode("artistMask"), "album-mask-342.png", [342, 342], [228, 228])
    m.artwork = m.top.findNode("artistArtwork")
    m.label = m.top.findNode("artistLabel")
end sub

'-------------------------------------------------------------------------------
' onItemContentChanged
'-------------------------------------------------------------------------------
sub onItemContentChanged()
    item = m.top.itemContent
    if item = invalid then return

    m.artwork.uri = Format.SafeString(item.HDPosterUrl, "")
    m.label.text = Format.FirstNonEmpty([item.title], "Unknown Artist")
end sub
