'-------------------------------------------------------------------------------
' init
'-------------------------------------------------------------------------------
sub init()
    m.background = m.top.findNode("background")
    m.focusBackground = m.top.findNode("focusBackground")
    m.selectedBackground = m.top.findNode("selectedBackground")
    m.letterLabel = m.top.findNode("letterLabel")
    m.top.observeField("focusedChild", "onFocusChanged")
    updateFocusVisual()
    onFocusChanged()
end sub

'-------------------------------------------------------------------------------
' onFocusChanged
'-------------------------------------------------------------------------------
sub onFocusChanged()
    m.top.itemHasFocus = m.top.isInFocusChain()
end sub

'-------------------------------------------------------------------------------
' onKeyEvent
'-------------------------------------------------------------------------------
function onKeyEvent(key as string, press as boolean) as boolean
    if press = false then return false
    if key = "OK" or key = "select" then
        m.top.buttonSelected = true
        return true
    end if
    return false
end function
