'-------------------------------------------------------------------------------
' init
'-------------------------------------------------------------------------------
sub init()
    m.castButton = m.top.findNode("castButton")
    m.subtitleButton = m.top.findNode("subtitleButton")
    m.audioButton = m.top.findNode("audioButton")
    m.videoButton = m.top.findNode("videoButton")
    m.playbackInfoButton = m.top.findNode("playbackInfoButton")
    m.chapterButton = m.top.findNode("chapterButton")
    m.skipBackButton = m.top.findNode("skipBackButton")
    m.playPauseButton = m.top.findNode("playPauseButton")
    m.skipForwardButton = m.top.findNode("skipForwardButton")
    m.last5Button = m.top.findNode("last5Button")
    m.trickplayPreview = m.top.findNode("trickplayPreview")
    m.metadataLabels = {
        title: m.top.findNode("titleLabel")
        subtitle: m.top.findNode("subtitleLabel")
    }
    m.progressBarGroup = m.top.findNode("progressBarGroup")
    m.progressFocusRect = m.top.findNode("progressFocusRect")
    m.progressBarBackground = m.top.findNode("progressBarBackground")
    m.progressBar = m.top.findNode("progressBar")
    m.previewBar = m.top.findNode("previewBar")
    m.scrubber = m.top.findNode("scrubber")
    m.positionLabel = m.top.findNode("positionLabel")
    m.remainingLabel = m.top.findNode("remainingLabel")

    m.controlState = {
        focusedIndex: 1
        focusArea: "buttons"
        buttons: []
    }
    m.optionButtonLayout = {
        startX: 102
        y: 962
        spacing: 95
    }
    m.playPauseIcons = {
        play: {
            icon: "pkg:/images/icons/playback-controls/play-unfocused.png"
            focusedIcon: "pkg:/images/icons/playback-controls/play-focused.png"
        }
        pause: {
            icon: "pkg:/images/icons/playback-controls/pause-unfocused.png"
            focusedIcon: "pkg:/images/icons/playback-controls/pause-focused.png"
        }
    }
    m.trickplayPositions = {
        default: [102, 420]
        tall: [102, 360]
    }

    colors = Theme.Get()
    m.metadataLabels.title.color = colors.text.light.primary
    m.metadataLabels.subtitle.color = colors.text.light.secondary

    m.castButton.icon = "pkg:/images/icons/playback-controls/person-unfocused.png"
    m.castButton.focusedIcon = "pkg:/images/icons/playback-controls/person-focused.png"
    m.subtitleButton.icon = "pkg:/images/icons/playback-controls/subtitles-unfocused.png"
    m.subtitleButton.focusedIcon = "pkg:/images/icons/playback-controls/subtitles-focused.png"
    m.audioButton.icon = "pkg:/images/icons/playback-controls/audio-unfocused.png"
    m.audioButton.focusedIcon = "pkg:/images/icons/playback-controls/audio-focused.png"
    m.videoButton.icon = "pkg:/images/icons/playback-controls/video-unfocused.png"
    m.videoButton.focusedIcon = "pkg:/images/icons/playback-controls/video-focused.png"
    m.playbackInfoButton.icon = "pkg:/images/icons/playback-controls/playback-info-unfocused.png"
    m.playbackInfoButton.focusedIcon = "pkg:/images/icons/playback-controls/playback-info-focused.png"
    m.chapterButton.icon = "pkg:/images/icons/playback-controls/chapters-unfocused.png"
    m.chapterButton.focusedIcon = "pkg:/images/icons/playback-controls/chapters-focused.png"
    m.skipBackButton.icon = "pkg:/images/icons/playback-controls/skip-back-unfocused.png"
    m.skipBackButton.focusedIcon = "pkg:/images/icons/playback-controls/skip-back-focused.png"
    m.skipForwardButton.icon = "pkg:/images/icons/playback-controls/skip-forward-unfocused.png"
    m.skipForwardButton.focusedIcon = "pkg:/images/icons/playback-controls/skip-forward-focused.png"

    m.castButton.observeField("buttonSelected", "onCastButtonSelected")
    m.subtitleButton.observeField("buttonSelected", "onSubtitleButtonSelected")
    m.audioButton.observeField("buttonSelected", "onAudioButtonSelected")
    m.videoButton.observeField("buttonSelected", "onVideoButtonSelected")
    m.playbackInfoButton.observeField("buttonSelected", "onPlaybackInfoButtonSelected")
    m.chapterButton.observeField("buttonSelected", "onChapterButtonSelected")
    m.skipBackButton.observeField("buttonSelected", "onSkipBackButtonSelected")
    m.playPauseButton.observeField("buttonSelected", "onPlayPauseButtonSelected")
    m.skipForwardButton.observeField("buttonSelected", "onSkipForwardButtonSelected")
    m.last5Button.observeField("buttonSelected", "onLast5ButtonSelected")
    m.top.observeField("focusedChild", "onFocusChanged")
    onTitleChanged()
    onSubtitleChanged()
    onPlayingChanged()
    onOptionsChanged()
    onSkipButtonAvailabilityChanged()
    updateButtonFocus()
end sub

'-------------------------------------------------------------------------------
' onTitleChanged
'-------------------------------------------------------------------------------
sub onTitleChanged()
    m.metadataLabels.title.text = Format.SafeString(m.top.title, "")
end sub

'-------------------------------------------------------------------------------
' onSubtitleChanged
'-------------------------------------------------------------------------------
sub onSubtitleChanged()
    m.metadataLabels.subtitle.text = Format.SafeString(m.top.subtitle, "")
end sub

'-------------------------------------------------------------------------------
' onProgressChanged
'-------------------------------------------------------------------------------
sub onProgressChanged()
    if m.top.isSeeking = true then return
    updateProgress(m.top.position, false)
end sub

'-------------------------------------------------------------------------------
' onPreviewChanged
'-------------------------------------------------------------------------------
sub onPreviewChanged()
    if m.top.isSeeking <> true then return
    updateProgress(m.top.previewPosition, true)
end sub

'-------------------------------------------------------------------------------
' onSeekingChanged
'-------------------------------------------------------------------------------
sub onSeekingChanged()
    m.previewBar.visible = m.top.isSeeking = true
    m.trickplayPreview.isSeeking = m.top.isSeeking
    if m.top.isSeeking = true then
        updateProgress(m.top.previewPosition, true)
    else
        updateProgress(m.top.position, false)
    end if
end sub

'-------------------------------------------------------------------------------
' onPlayingChanged
'-------------------------------------------------------------------------------
sub onPlayingChanged()
    if m.top.isPlaying = true then
        iconSet = m.playPauseIcons.pause
    else
        iconSet = m.playPauseIcons.play
    end if

    m.playPauseButton.icon = iconSet.icon
    m.playPauseButton.focusedIcon = iconSet.focusedIcon
end sub

'-------------------------------------------------------------------------------
' onOptionsChanged
'-------------------------------------------------------------------------------
sub onOptionsChanged()
    m.castButton.visible = m.top.hasCastOptions = true
    m.chapterButton.visible = m.top.hasChapterOptions = true
    m.subtitleButton.visible = m.top.hasSubtitleOptions = true
    m.audioButton.visible = m.top.hasAudioOptions = true
    m.videoButton.visible = m.top.hasVideoOptions = true
    layoutOptionButtons()
    rebuildButtonList()
end sub

'-------------------------------------------------------------------------------
' onSkipButtonAvailabilityChanged
'-------------------------------------------------------------------------------
sub onSkipButtonAvailabilityChanged()
    m.skipBackButton.enabled = m.top.skipBackEnabled <> false
    m.skipForwardButton.enabled = m.top.skipForwardEnabled <> false
    rebuildButtonList()
    if m.controlState.focusArea = "buttons" and m.top.isInFocusChain() = true then
        focusCurrentButton()
        return
    end if

    updateButtonFocus()
end sub

'-------------------------------------------------------------------------------
' layoutOptionButtons
'-------------------------------------------------------------------------------
sub layoutOptionButtons()
    x = m.optionButtonLayout.startX
    optionButtons = [m.chapterButton, m.castButton, m.subtitleButton, m.audioButton, m.videoButton, m.playbackInfoButton]
    for each button in optionButtons
        if button <> invalid and button.visible <> false then
            button.translation = [x, m.optionButtonLayout.y]
            x = x + m.optionButtonLayout.spacing
        end if
    end for
end sub

'-------------------------------------------------------------------------------
' onFocusChanged
'-------------------------------------------------------------------------------
sub onFocusChanged()
    if m.top.isInFocusChain() = true then
        if m.controlState.focusArea = "progress" then
            focusProgress()
        else
            focusCurrentButton()
        end if
    else
        updateProgressFocus()
        updateButtonFocus()
    end if
end sub

'-------------------------------------------------------------------------------
' onPlayPauseButtonSelected
'-------------------------------------------------------------------------------
sub onPlayPauseButtonSelected()
    m.top.playPausePressed = true
end sub

'-------------------------------------------------------------------------------
' onCastButtonSelected
'-------------------------------------------------------------------------------
sub onCastButtonSelected()
    m.top.castOptionsPressed = true
end sub

'-------------------------------------------------------------------------------
' onSubtitleButtonSelected
'-------------------------------------------------------------------------------
sub onSubtitleButtonSelected()
    m.top.subtitleOptionsPressed = true
end sub

'-------------------------------------------------------------------------------
' onAudioButtonSelected
'-------------------------------------------------------------------------------
sub onAudioButtonSelected()
    m.top.audioOptionsPressed = true
end sub

'-------------------------------------------------------------------------------
' onVideoButtonSelected
'-------------------------------------------------------------------------------
sub onVideoButtonSelected()
    m.top.videoOptionsPressed = true
end sub

'-------------------------------------------------------------------------------
' onPlaybackInfoButtonSelected
'-------------------------------------------------------------------------------
sub onPlaybackInfoButtonSelected()
    m.top.playbackInfoPressed = true
end sub

'-------------------------------------------------------------------------------
' onChapterButtonSelected
'-------------------------------------------------------------------------------
sub onChapterButtonSelected()
    m.top.chapterOptionsPressed = true
end sub

'-------------------------------------------------------------------------------
' onSkipBackButtonSelected
'-------------------------------------------------------------------------------
sub onSkipBackButtonSelected()
    if m.top.skipBackEnabled <> false then m.top.skipBackPressed = true
end sub

'-------------------------------------------------------------------------------
' onSkipForwardButtonSelected
'-------------------------------------------------------------------------------
sub onSkipForwardButtonSelected()
    if m.top.skipForwardEnabled <> false then m.top.skipForwardPressed = true
end sub

'-------------------------------------------------------------------------------
' onLast5ButtonSelected
'-------------------------------------------------------------------------------
sub onLast5ButtonSelected()
    m.top.last5Pressed = true
end sub

'-------------------------------------------------------------------------------
' moveButtonFocus
'-------------------------------------------------------------------------------
sub moveButtonFocus(direction as integer)
    rebuildButtonList()
    nextIndex = m.controlState.focusedIndex + direction
    if nextIndex < 0 then nextIndex = 0
    if nextIndex > m.controlState.buttons.Count() - 1 then nextIndex = m.controlState.buttons.Count() - 1

    m.controlState.focusedIndex = nextIndex
    focusCurrentButton()
end sub

'-------------------------------------------------------------------------------
' activate
'-------------------------------------------------------------------------------
sub activate()
    m.top.setFocus(true)
    if m.controlState.focusArea = "progress" then
        focusProgress()
    else
        focusCurrentButton()
    end if
end sub

'-------------------------------------------------------------------------------
' deactivate
'-------------------------------------------------------------------------------
sub deactivate()
    releaseFocus()
end sub

'-------------------------------------------------------------------------------
' resetFocus
'-------------------------------------------------------------------------------
sub resetFocus()
    rebuildButtonList(false)
    m.controlState.focusedIndex = PlaybackControlsLogic_GetDefaultButtonIndex(m.controlState.buttons)
    m.controlState.focusArea = "buttons"
end sub

'-------------------------------------------------------------------------------
' focusProgress
'-------------------------------------------------------------------------------
sub focusProgress()
    m.controlState.focusArea = "progress"
    m.progressBarGroup.setFocus(true)
    updateProgressFocus()
    updateButtonFocus()
end sub

'-------------------------------------------------------------------------------
' focusButtons
'-------------------------------------------------------------------------------
sub focusButtons()
    m.controlState.focusArea = "buttons"
    focusCurrentButton()
end sub

'-------------------------------------------------------------------------------
' focusCurrentButton
'-------------------------------------------------------------------------------
sub focusCurrentButton()
    m.controlState.focusArea = "buttons"
    rebuildButtonList()
    button = m.controlState.buttons[m.controlState.focusedIndex]
    if button <> invalid then button.setFocus(true)
    updateProgressFocus()
    updateButtonFocus()
end sub

'-------------------------------------------------------------------------------
' releaseFocus
'-------------------------------------------------------------------------------
sub releaseFocus()
    m.progressBarGroup.setFocus(false)
    allButtons = getAllButtons()
    for each button in allButtons
        if button <> invalid then button.setFocus(false)
    end for
    m.top.setFocus(false)
    updateProgressFocus()
    updateButtonFocus()
end sub

'-------------------------------------------------------------------------------
' getAllButtons
'-------------------------------------------------------------------------------
function getAllButtons() as object
    return [m.chapterButton, m.castButton, m.subtitleButton, m.audioButton, m.videoButton, m.playbackInfoButton, m.skipBackButton, m.playPauseButton, m.skipForwardButton, m.last5Button]
end function

'-------------------------------------------------------------------------------
' rebuildButtonList
'-------------------------------------------------------------------------------
sub rebuildButtonList(preserveFocusedButton = true as boolean)
    previousButtonId = ""
    if preserveFocusedButton = true and m.controlState.buttons.Count() > 0 and m.controlState.focusedIndex >= 0 and m.controlState.focusedIndex < m.controlState.buttons.Count() then
        previousButtonId = Format.SafeString(m.controlState.buttons[m.controlState.focusedIndex].id, "")
    end if

    buttons = []
    allButtons = getAllButtons()
    for each button in allButtons
        if button <> invalid and button.visible <> false and button.enabled <> false then buttons.Push(button)
    end for

    m.controlState.buttons = buttons
    if buttons.Count() = 0 then
        m.controlState.focusedIndex = 0
        return
    end if

    focusedIndex = -1
    if previousButtonId <> "" then
        for i = 0 to buttons.Count() - 1
            if Format.SafeString(buttons[i].id, "") = previousButtonId then
                focusedIndex = i
                exit for
            end if
        end for
    end if

    if focusedIndex < 0 then focusedIndex = PlaybackControlsLogic_GetDefaultButtonIndex(buttons)
    m.controlState.focusedIndex = focusedIndex
end sub

'-------------------------------------------------------------------------------
' updateButtonFocus
'-------------------------------------------------------------------------------
sub updateButtonFocus()
    allButtons = getAllButtons()
    for each button in allButtons
        if button <> invalid then button.hasFocusVisual = false
    end for

    for i = 0 to m.controlState.buttons.Count() - 1
        button = m.controlState.buttons[i]
        if button <> invalid then button.hasFocusVisual = i = m.controlState.focusedIndex and m.controlState.focusArea = "buttons" and m.top.isInFocusChain()
    end for
end sub

'-------------------------------------------------------------------------------
' updateProgressFocus
'-------------------------------------------------------------------------------
sub updateProgressFocus()
    m.progressFocusRect.visible = m.controlState.focusArea = "progress" and m.top.isInFocusChain()
end sub

'-------------------------------------------------------------------------------
' onThumbnailDataChanged
'-------------------------------------------------------------------------------
sub onThumbnailDataChanged()
    updateTrickplayPreviewPosition(m.top.thumbnailData)
    m.trickplayPreview.thumbnailData = m.top.thumbnailData
end sub

'-------------------------------------------------------------------------------
' updateTrickplayPreviewPosition
'-------------------------------------------------------------------------------
sub updateTrickplayPreviewPosition(data as dynamic)
    if VideoPlayerTrickplay_IsTallThumbnail(data) then
        m.trickplayPreview.translation = m.trickplayPositions.tall
    else
        m.trickplayPreview.translation = m.trickplayPositions.default
    end if
end sub

'-------------------------------------------------------------------------------
' updateProgress
'-------------------------------------------------------------------------------
sub updateProgress(position as dynamic, showPreview as boolean)
    progress = PlaybackControlsLogic_GetProgress(position, m.top.duration)
    progressWidth = m.progressBarBackground.width * progress.fraction
    if showPreview = true then
        m.previewBar.width = progressWidth
    else
        m.progressBar.width = progressWidth
    end if

    m.scrubber.translation = [progressWidth - 10, -7]
    m.positionLabel.text = PlaybackControlsLogic_FormatTime(progress.position)
    m.remainingLabel.text = "-" + PlaybackControlsLogic_FormatTime(progress.duration - progress.position)
end sub

'-------------------------------------------------------------------------------
' onKeyEvent
'-------------------------------------------------------------------------------
function onKeyEvent(key as string, press as boolean) as boolean
    if press = false then
        if m.controlState.focusArea = "progress" then
            if key = "left" then
                m.top.progressLeftReleased = true
                return true
            else if key = "right" then
                m.top.progressRightReleased = true
                return true
            end if
        end if

        return false
    end if

    if m.controlState.focusArea = "progress" then
        if key = "left" then
            m.top.progressLeftPressed = true
            return true
        else if key = "right" then
            m.top.progressRightPressed = true
            return true
        else if key = "rewind" then
            m.top.progressRewindPressed = true
            return true
        else if key = "fastforward" then
            m.top.progressFastForwardPressed = true
            return true
        else if key = "OK" or key = "play" then
            if m.top.isSeeking = true then
                m.top.progressSeekCommit = true
                return true
            end if

            return false
        else if key = "back" then
            if m.top.isSeeking = true then
                m.top.progressSeekCancel = true
                return true
            end if

            return false
        else if key = "down" then
            focusButtons()
            return true
        end if

        return false
    end if

    if key = "left" then
        moveButtonFocus(-1)
        return true
    else if key = "right" then
        moveButtonFocus(1)
        return true
    else if key = "up" then
        focusProgress()
        return true
    else if key = "down" then
        m.top.focusExitDown = true
        return true
    else if key = "play" then
        m.top.playPausePressed = true
        return true
    end if

    return false
end function
