import "pkg:/source/Remote.bs"

'-------------------------------------------------------------------------------
' init
'-------------------------------------------------------------------------------
sub init()
    initReferences()
    initHandlers()
end sub

'-------------------------------------------------------------------------------
' initReferences
'-------------------------------------------------------------------------------
sub initReferences()
    m.buttons = { cancel: m.top.findNode("cancel"), send: m.top.findNode("send") }
end sub

'-------------------------------------------------------------------------------
' initHandlers
'-------------------------------------------------------------------------------
sub initHandlers()
    m.buttons.cancel.observeField("buttonSelected", "onCancel")
    m.buttons.send.observeField("buttonSelected", "onSend")
end sub

'-------------------------------------------------------------------------------
' focusCancel
'-------------------------------------------------------------------------------
sub focusCancel()
    m.buttons.cancel.hasFocusVisual = true
    m.buttons.send.hasFocusVisual = false
    m.buttons.cancel.setFocus(true)
end sub

'-------------------------------------------------------------------------------
' onCancel
'-------------------------------------------------------------------------------
sub onCancel()
    m.top.decision = false
end sub

'-------------------------------------------------------------------------------
' onSend
'-------------------------------------------------------------------------------
sub onSend()
    m.top.decision = true
end sub

'-------------------------------------------------------------------------------
' onKeyEvent
'-------------------------------------------------------------------------------
function onKeyEvent(key as string, press as boolean) as boolean
    if not press then return false
    if key = Remote.Key.Back then
        onCancel()
    else if key = Remote.Key.Left then
        focusCancel()
    else if key = Remote.Key.Right then
        m.buttons.cancel.hasFocusVisual = false
        m.buttons.send.hasFocusVisual = true
        m.buttons.send.setFocus(true)
    else
        return false
    end if
    return true
end function
