import "pkg:/source/Char.bs"

namespace TestMediaAuthentication

    '---------------------------------------------------------------------------
    ' TestMediaAuthentication.ExpectedHeader
    '---------------------------------------------------------------------------
    function ExpectedHeader(token as string, userId = "" as string) as string
        device = CreateObject("roDeviceInfo")
        app = CreateObject("roAppInfo")
        quote = Char.DoubleQuote
        deviceName = device.GetModelDisplayName()
        if deviceName = "" then deviceName = device.GetModel()
        deviceId = device.GetChannelClientId()
        if deviceId = "" then deviceId = device.GetModel()
        expected = "Authorization: MediaBrowser Client=" + quote + "Starfin Roku" + quote
        expected += ", Device=" + quote + deviceName + quote
        expected += ", Version=" + quote + app.GetVersion() + quote
        expected += ", DeviceId=" + quote + deviceId + quote
        if userId <> "" then expected += ", UserId=" + quote + userId + quote
        expected += ", Token=" + quote + token + quote
        return expected
    end function

end namespace
