'-------------------------------------------------------------------------------
' init
'-------------------------------------------------------------------------------
sub init()
    m.showLogo = m.top.findNode("showLogo")
    m.seriesLabel = m.top.findNode("seriesLabel")
    render()
end sub

'-------------------------------------------------------------------------------
' render
'-------------------------------------------------------------------------------
sub render()

    ' logo
    logoUrl = m.top.logoUrl
    m.showLogo.visible = logoUrl <> ""
    m.showLogo.uri = logoUrl

    ' fallback label (no logo)
    m.seriesLabel.visible = logoUrl = ""
    m.seriesLabel.text = m.top.title
end sub
