namespace tests

    @SGNode("SettingsDialog")
    @suite("SettingsDialog component")
    class SettingsDialogTests extends rooibos.BaseTestSuite

        @describe("dialog behavior")

        @it("configures settings content")
        function _()
            m.top.accountKey = "rooibos-settings-dialog-read-only"

            m.top.callFunc("openSettings")

            m.assertEqual(m.top.title, "Settings")
            m.assertTrue(m.top.dialogWidth = 1560)
            m.assertTrue(m.top.dialogHeight = 900)
            m.assertEqual(m.top.contentComponentName, "SettingsContent")
        end function

        @it("keeps content selection from closing settings")
        function _()
            m.top.accountKey = "rooibos-settings-dialog-read-only"

            m.top.callFunc("openSettings")

            m.assertFalse(m.top.closeOnContentSelected)
        end function

        @it("passes the account key to settings content")
        function _()
            m.top.accountKey = "rooibos-settings-dialog-read-only"

            m.top.callFunc("openSettings")
            content = m.top.callFunc("getContentComponent")

            m.assertEqual(content.accountKey, "rooibos-settings-dialog-read-only")
        end function

        @it("opens the settings dialog")
        function _()
            m.top.accountKey = "rooibos-settings-dialog-read-only"

            m.top.callFunc("openSettings")

            m.assertTrue(m.top.findNode("dialog").visible)
        end function

        @it("focuses settings content")
        function _()
            m.top.accountKey = "rooibos-settings-dialog-read-only"

            m.top.callFunc("openSettings")
            content = m.top.callFunc("getContentComponent")

            m.assertTrue(content.isInFocusChain())
        end function

        @it("propagates reset confirmation and closes")
        function _()
            m.top.accountKey = "rooibos-settings-dialog-read-only"
            m.top.resetStarfinConfirmed = false
            m.top.callFunc("openSettings")

            'bs:disable-next-line 1140
            onResetStarfinConfirmed()

            m.assertTrue(m.top.resetStarfinConfirmed)
            m.assertFalse(m.top.findNode("dialog").visible)
        end function

    end class

end namespace
