import "pkg:/source/ResolutionProfile.bs"
import "pkg:/source/ResolutionAssets.bs"
import "pkg:/source/TimerControl.bs"
import "pkg:/source/SpinnerControl.bs"
import "pkg:/source/BusySpinnerControl.bs"

'-------------------------------------------------------------------------------
' init
'-------------------------------------------------------------------------------
sub init()
    m.scrim = m.top.findNode("scrim")
    m.spinner = m.top.findNode("spinner")
    m.showDelayTimer = m.top.findNode("showDelayTimer")

    m.spinner.uri = ResolutionAssets.GetIconImageUri("busy-spinner.png")
    m.showDelayTimer.observeField("fire", "onShowDelayTimerFire")
    m.top.visible = false
    setVisualsVisible(false)
end sub

'-------------------------------------------------------------------------------
' onControlChanged
'-------------------------------------------------------------------------------
sub onControlChanged()
    control = LCase(m.top.control)
    if control = SpinnerControl.Command.Start then
        startSpinner()
    else if control = SpinnerControl.Command.Stop then
        stopSpinner()
    end if
end sub

'-------------------------------------------------------------------------------
' onShowDelayTimerFire
'-------------------------------------------------------------------------------
sub onShowDelayTimerFire()
    showSpinner()
end sub

'-------------------------------------------------------------------------------
' startSpinner
'-------------------------------------------------------------------------------
sub startSpinner()
    m.showDelayTimer.control = TimerControl.Command.Stop
    delay = m.top.showDelay

    m.top.visible = true
    if delay <= 0 then
        showSpinner()
        return
    end if

    setVisualsVisible(false)
    m.spinner.control = BusySpinnerControl.Command.Stop
    m.showDelayTimer.duration = delay
    m.showDelayTimer.control = TimerControl.Command.Start
end sub

'-------------------------------------------------------------------------------
' stopSpinner
'-------------------------------------------------------------------------------
sub stopSpinner()
    m.showDelayTimer.control = TimerControl.Command.Stop
    m.spinner.control = BusySpinnerControl.Command.Stop
    setVisualsVisible(false)
    m.top.visible = false
end sub

'-------------------------------------------------------------------------------
' showSpinner
'-------------------------------------------------------------------------------
sub showSpinner()
    m.top.visible = true
    setVisualsVisible(true)
    m.spinner.control = BusySpinnerControl.Command.Start
end sub

'-------------------------------------------------------------------------------
' setVisualsVisible
'-------------------------------------------------------------------------------
sub setVisualsVisible(isVisible as boolean)
    m.scrim.visible = isVisible
    m.spinner.visible = isVisible
end sub

'-------------------------------------------------------------------------------
' onKeyEvent
'-------------------------------------------------------------------------------
function onKeyEvent(key as string, press as boolean) as boolean
    return m.top.blockInteraction = true
end function
