import "pkg:/source/RemotePlayback.bs"
import "pkg:/source/MediaItem.bs"

'-------------------------------------------------------------------------------
' remotePlaybackHandleSelected
'-------------------------------------------------------------------------------
sub remotePlaybackHandleSelected(event as object)
    remotePlaybackStart(event.getRoSGNode(), event.getData())
end sub

'-------------------------------------------------------------------------------
' remotePlaybackStart
'-------------------------------------------------------------------------------
sub remotePlaybackStart(origin as object, selection as dynamic)
    if selection = invalid or origin.visible <> true or origin.isInFocusChain() <> true then return
    if RemotePlayback.BuildSelection(selection.item) = invalid then return
    if (m.loadingSpinner.visible and m.loadingSpinner.blockInteraction) then return
    if m.overlayHost.isInFocusChain() or m.messageOverlayHost.isInFocusChain() or m.confirmationOverlayHost.isInFocusChain() then return
    if selection.item.Type = MediaItem.Type.MusicAlbum then
        musicAudioPlayerShow(selection, origin)
    else
        playerShow(selection, origin)
    end if
end sub
