import "pkg:/source/Remote.bs"
import "pkg:/source/Format.bs"
import "pkg:/source/String.bs"

'-------------------------------------------------------------------------------
' init
'-------------------------------------------------------------------------------
sub init()
    m.overview = m.top.findNode("overview")
    renderOverview()
end sub

'-------------------------------------------------------------------------------
' focusOverview
'-------------------------------------------------------------------------------
sub focusOverview()
    m.overview.setFocus(true)
end sub

'-------------------------------------------------------------------------------
' onOverviewTextChanged
'-------------------------------------------------------------------------------
sub onOverviewTextChanged()
    renderOverview()
end sub

'-------------------------------------------------------------------------------
' renderOverview
'-------------------------------------------------------------------------------
sub renderOverview()
    m.overview.text = Format.SafeString(m.top.overviewText, "")
end sub

'-------------------------------------------------------------------------------
' onKeyEvent
'-------------------------------------------------------------------------------
function onKeyEvent(key as string, press as boolean) as boolean
    if press = false then return false
    if key = Remote.Key.OK or key = Remote.Key.Select then return true

    return false
end function
