import "pkg:/source/Format.bs"
import "pkg:/source/String.bs"

'-------------------------------------------------------------------------------
' init
'-------------------------------------------------------------------------------
sub init()
    initBase()
    m.top.placeholderUri = "pkg:/images/media-card/thumbnail-placeholder-441x249.png"
    m.top.callFunc("applyCardLayout", {
        contentTranslation: [27, 0], posterMaskName: "media-card-jumbo-mask.png"
        posterSize: [882, 496], hdPosterSize: [588, 331], posterTranslation: [0, 0]
        progressTranslation: [29, 449], progressWidth: 824, progressHeight: 18
        watchedTranslation: [807, 18], watchedSize: 57
        title: { translation: [0, 508], width: 882, height: 34, numLines: 1 }
        metadata: { translation: [0, 544], width: 882, height: 42, numLines: 2 }
    })
    m.cardNodes.titleLogo.translation = [30, 306]
    m.cardNodes.titleLogo.width = 360
    m.cardNodes.titleLogo.height = 140
end sub

'-------------------------------------------------------------------------------
' renderPresentation
'-------------------------------------------------------------------------------
sub renderPresentation(content as object)
    renderStandardText(content)
    logoUrl = Format.SafeString(content.logoUrl, "")
    m.cardNodes.titleLogo.uri = logoUrl
    m.cardNodes.titleLogo.visible = logoUrl <> ""
end sub
