'-------------------------------------------------------------------------------
' openVideoMediaInfo
'-------------------------------------------------------------------------------
sub openVideoMediaInfo()
    m.top.title = "Media Information"
    m.top.dialogWidth = 1200
    m.top.dialogHeight = 940
    m.top.contentComponentName = "VideoMediaInfoContent"
    onItemChanged()
    m.top.callFunc("openDialog")
end sub

'-------------------------------------------------------------------------------
' onItemChanged
'-------------------------------------------------------------------------------
sub onItemChanged()
    content = m.top.callFunc("getContentComponent")
    if content <> invalid then content.item = m.top.item
end sub
