namespace tests

    @SGNode("SystemInformationDialog")
    @suite("SystemInformationDialog component")
    class SystemInformationDialogTests extends rooibos.BaseTestSuite

        @describe("dialog behavior")

        @it("configures system information content")
        function _()
            m.top.callFunc("openSystemInformation")

            m.assertEqual(m.top.title, "System Information")
            m.assertTrue(m.top.dialogWidth = 1536)
            m.assertTrue(m.top.dialogHeight = 940)
            m.assertEqual(m.top.contentComponentName, "SystemInformationContent")
        end function

        @it("opens the dialog")
        function _()
            m.top.callFunc("openSystemInformation")

            m.assertTrue(m.top.findNode("dialog").visible)
        end function

        @it("focuses system information content")
        function _()
            m.top.callFunc("openSystemInformation")
            content = m.top.callFunc("getContentComponent")

            m.assertTrue(content.isInFocusChain())
        end function

        @it("renders system information rows")
        function _()
            m.top.callFunc("openSystemInformation")
            content = m.top.callFunc("getContentComponent")

            m.assertTrue(content.findNode("propertySheet").getChildCount() > 0)
        end function

    end class

end namespace
