'-------------------------------------------------------------------------------
' init
'-------------------------------------------------------------------------------
sub init()
    initBase()
    m.top.placeholderUri = "pkg:/images/media-card/thumbnail-placeholder-441x249.png"
    m.top.callFunc("applyCardLayout", {
        contentTranslation: [21, 0], posterMaskName: "media-card-thumbnail-mask.png"
        posterSize: [441, 249], hdPosterSize: [294, 166], posterTranslation: [0, 0]
        progressTranslation: [9, 231], progressWidth: 423, progressHeight: 9
        watchedTranslation: [375, 9], watchedSize: 57
        title: { translation: [0, 261], width: 441, height: 34, numLines: 1 }
        metadata: { translation: [0, 297], width: 441, height: 42, numLines: 2 }
    })
end sub

'-------------------------------------------------------------------------------
' renderPresentation
'-------------------------------------------------------------------------------
sub renderPresentation(content as object)
    renderStandardText(content)
    m.cardNodes.title.height = 34
    m.cardNodes.title.numLines = 1
    if content.showMetadata = false then
        m.cardNodes.title.height = 48
        m.cardNodes.title.numLines = 2
    end if
end sub
