'-------------------------------------------------------------------------------
' init
'-------------------------------------------------------------------------------
sub init()
    m.chevronIcon = m.top.findNode("chevronIcon")
    onDimensionsChanged()
    onDirectionChanged()
end sub

'-------------------------------------------------------------------------------
' onDirectionChanged
'-------------------------------------------------------------------------------
sub onDirectionChanged()
    direction = LCase(Format.SafeString(m.top.direction, ""))
    if direction = "up" or direction = "down" or direction = "left" or direction = "right" then
        m.chevronIcon.uri = "pkg:/images/icons/chevrons/" + direction + ".png"
        m.chevronIcon.visible = true
    else
        m.chevronIcon.visible = false
    end if
end sub

'-------------------------------------------------------------------------------
' onDimensionsChanged
'-------------------------------------------------------------------------------
sub onDimensionsChanged()
    width = int(m.top.iconWidth)
    height = int(m.top.iconHeight)
    if width <= 0 then width = 48
    if height <= 0 then height = 48

    m.chevronIcon.width = width
    m.chevronIcon.height = height
end sub
