import "pkg:/source/RequestFailure.bs"
import "pkg:/source/JellyfinImage.bs"
import "pkg:/source/String.bs"
import "pkg:/source/Logger.bs"
import "pkg:/source/Encode.bs"
import "pkg:/source/Url.bs"
import "pkg:/source/api/HttpClient.bs"
import "pkg:/source/api/JellyfinAuth.bs"
import "pkg:/source/TaskRequest.bs"
import "pkg:/source/TaskResponse.bs"

'-------------------------------------------------------------------------------
' init
'-------------------------------------------------------------------------------
sub init()
    m.log = new Logger("ContinueWatchingTask", m.global.logService)
    m.top.functionName = "executeRequest"
end sub

'-------------------------------------------------------------------------------
' executeRequest
'-------------------------------------------------------------------------------
sub executeRequest()
    try
        request = m.top.request
        validationError = TaskRequest.ValidateRequest(request, "continueWatching")
        if validationError <> invalid then
            m.top.response = validationError
            return
        end if

        params = buildContinueWatchingParams()

        requestUrl = request.server + "/useritems/resume" + Url.BuildQueryString(params)
        response = HttpClient.Request(requestUrl, "GET", invalid, invalid, JellyfinAuth.BuildTokenHeaders(request.token))
        if response.ok <> true then
            m.top.response = TaskResponse.Failure(response, "continueWatching")
            return
        end if

        m.top.response = TaskResponse.Success(request, "continueWatching", response.data)
    catch error
        m.log.error("Unable to load Continue Watching. Error=" + error.number.ToStr())
        failure = {
            ok: false
            action: "continueWatching"
            failureKind: RequestFailure.Kind.UnexpectedResponse
            errorMessage: "Unable to load Continue Watching."
        }
        m.top.response = failure
    end try
end sub

'-------------------------------------------------------------------------------
' buildContinueWatchingParams
'-------------------------------------------------------------------------------
function buildContinueWatchingParams() as object
    return {
        recursive: true
        SortBy: "DatePlayed"
        SortOrder: "Descending"
        Filters: "IsResumable"
        MediaTypes: "Video"
        excludeItemTypes: "Book,MusicVideo"
        Fields: "SeriesInfo"
        EnableImageTypes: Strings.Join([JellyfinImage.Type.Primary, JellyfinImage.Type.Backdrop, JellyfinImage.Type.Thumb, JellyfinImage.Type.Logo])
        ImageTypeLimit: 1
        EnableTotalRecordCount: false
    }
end function
