import "pkg:/source/Format.bs"
import "pkg:/source/String.bs"
import "pkg:/source/Logger.bs"
import "pkg:/source/Encode.bs"
import "pkg:/source/Url.bs"
import "pkg:/source/api/HttpClient.bs"
import "pkg:/source/api/JellyfinAuth.bs"
import "pkg:/source/TaskRequest.bs"
import "pkg:/source/TaskResponse.bs"

'-------------------------------------------------------------------------------
' init
'-------------------------------------------------------------------------------
sub init()
    m.log = new Logger("ContinueWatchingTask", m.global.logService)
    m.top.functionName = "executeRequest"
end sub

'-------------------------------------------------------------------------------
' executeRequest
'-------------------------------------------------------------------------------
sub executeRequest()
    request = m.top.request
    validationError = TaskRequest.ValidateRequest(request, "continueWatching")
    if validationError <> invalid then
        m.top.response = validationError
        return
    end if

    params = {
        recursive: true
        SortBy: "DatePlayed"
        SortOrder: "Descending"
        Filters: "IsResumable"
        MediaTypes: "Video"
        excludeItemTypes: "Book"
        Fields: "SeriesInfo"
        EnableImageTypes: "Primary,Backdrop,Thumb"
        ImageTypeLimit: 1
        EnableTotalRecordCount: false
    }

    requestUrl = request.server + "/useritems/resume" + Url.BuildQueryString(params)
    response = HttpClient.Request(requestUrl, "GET", invalid, invalid, JellyfinAuth.BuildTokenHeaders(request.token))
    if response.ok <> true then
        m.top.response = TaskResponse.Failure(response, "continueWatching")
        return
    end if

    m.top.response = TaskResponse.Success(request, "continueWatching", response.data)
end sub
