import "pkg:/source/String.bs"
import "pkg:/source/Url.bs"
import "pkg:/source/api/HttpClient.bs"
import "pkg:/source/api/JellyfinAuth.bs"

namespace JellyfinMovie

    '---------------------------------------------------------------------------
    ' JellyfinMovie.Load
    '---------------------------------------------------------------------------
    function Load(request as object) as object
        params = { userId: Strings.ToString(request.userId), fields: "Chapters,Trickplay,Genres,People,MediaSources,MediaStreams,Overview,UserData" }
        requestUrl = request.server + "/Items/" + request.itemId + Url.BuildQueryString(params)
        return HttpClient.Request(requestUrl, "GET", invalid, invalid, JellyfinAuth.BuildTokenHeaders(request.token))
    end function

end namespace
