import "pkg:/source/Format.bs"
import "pkg:/source/Number.bs"
import "pkg:/source/String.bs"
import "pkg:/source/Logger.bs"
import "pkg:/source/Encode.bs"
import "pkg:/source/Url.bs"
import "pkg:/source/api/HttpClient.bs"
import "pkg:/source/api/JellyfinAuth.bs"
import "pkg:/source/TaskRequest.bs"
import "pkg:/source/TaskResponse.bs"

'-------------------------------------------------------------------------------
' init
'-------------------------------------------------------------------------------
sub init()
    m.top.functionName = "executeRequest"
end sub

'-------------------------------------------------------------------------------
' executeRequest
'-------------------------------------------------------------------------------
sub executeRequest()
    request = m.top.request
    validationError = TaskRequest.ValidateRequest(request, "latestMedia")
    if validationError <> invalid then
        m.top.response = validationError
        return
    end if

    params = {
        userId: TaskRequest.GetUserId(request)
        limit: Number.ToInteger(request.limit, 25)
        parentId: Format.SafeString(request.parentId, "")
        enableImageTypes: "Primary, Backdrop, Thumb"
        imageTypeLimit: 1
        enableTotalRecordCount: false
        fields: "Genres"
    }

    requestUrl = request.server + "/items/latest" + Url.BuildQueryString(params)
    response = HttpClient.Request(requestUrl, "GET", invalid, invalid, JellyfinAuth.BuildTokenHeaders(request.token))
    if response.ok <> true then
        m.top.response = TaskResponse.Failure(response, "latestMedia")
        return
    end if

    successResponse = TaskResponse.Success(request, "latestMedia", response.data)
    successResponse.AddReplace("parentId", Format.SafeString(request.parentId, ""))
    m.top.response = successResponse
end sub
