'-------------------------------------------------------------------------------
' openPlayback
'-------------------------------------------------------------------------------
sub openPlayback()
    m.top.title = "Playback Options"
    m.top.dialogWidth = 606
    m.top.dialogHeight = 650
    m.top.showButtons = false
    m.top.contentComponentName = "HomeVideoPlaybackContent"
    content = m.top.callFunc("getContentComponent")
    content.itemImageUrl = m.top.itemImageUrl
    content.item = m.top.item
    content.observeField("selectedVideo", "onVideoSelected")
    m.top.callFunc("openDialog")
    content.callFunc("activate")
end sub

'-------------------------------------------------------------------------------
' onVideoSelected
'-------------------------------------------------------------------------------
sub onVideoSelected(event as object)
    m.top.selectedVideo = event.getData()
    m.top.callFunc("closeDialog")
end sub
