namespace AppMessage

    '---------------------------------------------------------------------------
    ' AppMessage.Show
    '---------------------------------------------------------------------------
    sub Show(message as string)
        scene = m.top.getScene()
        if scene <> invalid then scene.callFunc("showMessage", message)
    end sub

    '---------------------------------------------------------------------------
    ' AppMessage.Dismiss
    '---------------------------------------------------------------------------
    sub Dismiss()
        scene = m.top.getScene()
        if scene <> invalid then scene.callFunc("dismissMessage")
    end sub

end namespace
