namespace Arrays

    '---------------------------------------------------------------------------
    ' Arrays.GetCount
    '---------------------------------------------------------------------------
    function GetCount(values as dynamic) as integer

        if values = invalid then return 0
        
        valueType = Type(values)
        if valueType <> "roArray" and valueType <> "roAssociativeArray" then return 0
        
        return values.Count()

    end function

    '---------------------------------------------------------------------------
    ' Arrays.IsAssocArray
    '---------------------------------------------------------------------------
    function IsAssocArray(value as dynamic) as boolean
        valueType = Type(value)
        return valueType = "roAssociativeArray" or valueType = "roSGNodeEvent"
    end function

    '---------------------------------------------------------------------------
    ' Arrays.JoinStringValues
    '---------------------------------------------------------------------------
    ' Example: ["one", "two", "three"] returns "one, two, three".
    '---------------------------------------------------------------------------
    function JoinStringValues(values as dynamic) as string

        if values = invalid then return ""

        result = ""
        for each value in values
            if result <> "" then result = result + ", "
            result = result + Format.SafeString(value, "")
        end for

        return result

    end function

end namespace
