namespace Number

    '---------------------------------------------------------------------------
    ' Number.ToFloat
    '---------------------------------------------------------------------------
    function ToFloat(value as dynamic, fallback = 0.0 as float) as float
        if value = invalid then return fallback
        if Number.__IsNumericType(Type(value)) then return value
        return val(value.ToStr())
    end function

    '---------------------------------------------------------------------------
    ' Number.ToInteger
    '---------------------------------------------------------------------------
    function ToInteger(value as dynamic, fallback = 0 as integer) as integer
        if value = invalid then return fallback
        if Number.__IsNumericType(Type(value)) then return int(value)
        return int(val(value.ToStr()))
    end function

    '---------------------------------------------------------------------------
    ' Number.__IsNumericType
    '---------------------------------------------------------------------------
    function __IsNumericType(valueType as string) as boolean
        if valueType = "Integer" or valueType = "roInt" then return true
        if valueType = "LongInteger" or valueType = "roLongInteger" then return true
        if valueType = "Float" or valueType = "roFloat" then return true
        if valueType = "Double" or valueType = "roDouble" then return true

        return false
    end function

    '---------------------------------------------------------------------------
    ' Number.FormatWithThousandsSeparator
    '---------------------------------------------------------------------------
    function FormatWithThousandsSeparator(value as dynamic) as string
        if value = invalid then return ""

        text = value.ToStr()
        result = ""

        while Len(text) > 3
            result = "," + Right(text, 3) + result
            text = Left(text, Len(text) - 3)
        end while

        return text + result
    end function

end namespace
