namespace PlaybackAction

    enum Mode
        None = "none"
        RandomSkip = "randomSkip"
        SkipIntro = "skipIntro"
        SkipCredits = "skipCredits"
        PlayNext = "playNext"
    end enum

    enum Source
        None = "none"
        IntroSegment = "intro-segment"
        OutroSegment = "outro-segment"
        NextEpisodeSetting = "next-episode-setting"
    end enum

end namespace
