namespace ResolutionAssets

    '---------------------------------------------------------------------------
    ' ResolutionAssets.GetButtonImageUri
    '---------------------------------------------------------------------------
    function GetButtonImageUri(filename as string) as string
        return ResolutionAssets.__GetImageUri("buttons", filename)
    end function

    '---------------------------------------------------------------------------
    ' ResolutionAssets.GetHeaderImageUri
    '---------------------------------------------------------------------------
    function GetHeaderImageUri(filename as string) as string
        return ResolutionAssets.__GetImageUri("header", filename)
    end function

    '---------------------------------------------------------------------------
    ' ResolutionAssets.GetHomepageImageUri
    '---------------------------------------------------------------------------
    function GetHomepageImageUri(filename as string) as string
        return ResolutionAssets.__GetImageUri("homepage", filename)
    end function

    '---------------------------------------------------------------------------
    ' ResolutionAssets.GetIconImageUri
    '---------------------------------------------------------------------------
    function GetIconImageUri(filename as string) as string
        return ResolutionAssets.__GetImageUri("icons", filename)
    end function

    '---------------------------------------------------------------------------
    ' ResolutionAssets.GetMaskImageUri
    '---------------------------------------------------------------------------
    function GetMaskImageUri(filename as string) as string
        return ResolutionAssets.__GetImageUri("masks", filename)
    end function

    '---------------------------------------------------------------------------
    ' ResolutionAssets.GetLibraryImageUri
    '---------------------------------------------------------------------------
    function GetLibraryImageUri(filename as string) as string
        return ResolutionAssets.__GetImageUri("library", filename)
    end function

    '---------------------------------------------------------------------------
    ' ResolutionAssets.__GetImageUri
    '---------------------------------------------------------------------------
    function __GetImageUri(category as string, filename as string) as string
        return "pkg:/images/" + category + "/" + ResolutionProfile.GetName() + "/" + filename
    end function

end namespace
