import "pkg:/source/SpinnerControl.bs"

namespace Spinner

    '---------------------------------------------------------------------------
    ' Spinner.Show
    '---------------------------------------------------------------------------
    sub Show(showDelay = invalid as dynamic)
        spinnerNode = __GetNode()
        if spinnerNode.blockInteraction = true and showDelay <> 0 then return

        resolvedShowDelay = 2.0
        if showDelay <> invalid then resolvedShowDelay = showDelay

        spinnerNode.showDelay = resolvedShowDelay
        spinnerNode.control = SpinnerControl.Command.Start
    end sub

    '---------------------------------------------------------------------------
    ' Spinner.ShowBlocking
    '---------------------------------------------------------------------------
    sub ShowBlocking()
        spinnerNode = __GetNode()
        spinnerNode.blockInteraction = true
        spinnerNode.showDelay = 0
        spinnerNode.control = SpinnerControl.Command.Start
        spinnerNode.setFocus(true)
    end sub

    '---------------------------------------------------------------------------
    ' Spinner.Hide
    '---------------------------------------------------------------------------
    sub Hide()
        spinnerNode = __GetNode()
        if spinnerNode.blockInteraction = true then return

        spinnerNode.control = SpinnerControl.Command.Stop
        spinnerNode.visible = false
    end sub

    '---------------------------------------------------------------------------
    ' Spinner.HideBlocking
    '---------------------------------------------------------------------------
    sub HideBlocking()
        spinnerNode = __GetNode()
        spinnerNode.blockInteraction = false
        spinnerNode.control = SpinnerControl.Command.Stop
        spinnerNode.visible = false
    end sub

    '---------------------------------------------------------------------------
    ' Spinner.__GetNode
    '---------------------------------------------------------------------------
    function __GetNode() as dynamic
        if m = invalid or m.top = invalid then return invalid

        scene = m.top.getScene()
        if scene = invalid then return invalid

        return scene.findNode("loadingSpinner")
    end function

end namespace
