namespace Spinner

    '---------------------------------------------------------------------------
    ' Spinner.Show
    '---------------------------------------------------------------------------
    sub Show(showDelay = invalid as dynamic)
        spinnerNode = __GetNode()
        if spinnerNode = invalid then return
        if spinnerNode.blockInteraction = true and showDelay <> 0 then return

        resolvedShowDelay = 2.0
        if showDelay <> invalid then resolvedShowDelay = showDelay

        spinnerNode.showDelay = resolvedShowDelay
        spinnerNode.control = "start"
    end sub

    '---------------------------------------------------------------------------
    ' Spinner.Hide
    '---------------------------------------------------------------------------
    sub Hide()
        spinnerNode = __GetNode()
        if spinnerNode = invalid then return
        if spinnerNode.blockInteraction = true then return

        spinnerNode.control = "stop"
        spinnerNode.visible = false
    end sub

    '---------------------------------------------------------------------------
    ' Spinner.__GetNode
    '---------------------------------------------------------------------------
    function __GetNode() as dynamic
        if m = invalid or m.top = invalid then return invalid

        scene = m.top.getScene()
        if scene = invalid then return invalid

        return scene.findNode("loadingSpinner")
    end function

end namespace
