'-------------------------------------------------------------------------------
' applySortSelection
'-------------------------------------------------------------------------------
function applySortSelection(selection as object) as boolean
    m.top.appliedSelection = selection
    return m.top.deferFocus
end function

'-------------------------------------------------------------------------------
' focusFilterButtonRow
'-------------------------------------------------------------------------------
function focusFilterButtonRow() as boolean
    m.top.filterFocusRequested = true
    return true
end function

'-------------------------------------------------------------------------------
' focusBrowseByButton
'-------------------------------------------------------------------------------
function focusBrowseByButton() as boolean
    m.top.browseFocusRequested = true
    return true
end function
